stages:
  - test
  - style
  - deploy

api:
  stage: test
  image: rust:1.31
  variables:
    CARGO_HOME: "$CI_PROJECT_DIR/cargo"
  except:
    - master
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends libpq-dev
  script:
    - cd services/api
    - du -hs target || true
    - du -hs cargo || true
    - echo "$CARGO_HOME" && rustc --version && cargo --version && rustup --version
    - cargo build --verbose
    - cargo test --verbose --jobs 1
  cache:
    paths:
      - services/api/target/
      - cargo/

web:
  stage: test
  image: node:10
  except:
    - master
  script:
    - cd services/web
    - du -hs node_modules || true
    - node --version && npm --version
    - npm install
    - npm audit || true
    - npm run build
  cache:
    paths:
      - services/web/node_modules/

get:
  stage: test
  image: golang:1.11
  except:
    - master
  script:
    - cd services/get
    - du -hs .gopath || true
    - go version
    - make build
  cache:
    paths:
      - services/get/.gopath/

sync:
  stage: test
  image: golang:1.11
  except:
    - master
  script:
    - cd services/sync
    - du -hs .gopath || true
    - go version
    - make build
  cache:
    paths:
      - services/sync/.gopath/

api-rustfmt:
  stage: style
  image: rust:latest
  except:
    - master
  allow_failure: true
  script:
    - cd services/api
    - rustc --version && cargo --version && rustup --version
    - rustup component add rustfmt-preview
    - rustfmt --check services/api/src/**.rs

web-tslint:
  stage: style
  image: node:10
  except:
    - master
  allow_failure: true
  script:
    - cd services/web
    - node --version && npm --version
    - npm install tslint tslint-react typescript
    - ./node_modules/.bin/tslint -c tslint.json 'src/**/*.{ts,tsx}'

docker:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ( cd services/api  && docker build . -f ./Dockerfile -t $CI_REGISTRY_IMAGE/api:latest )
    - ( cd services/api  && docker build . -f ./Dockerfile-migrate -t $CI_REGISTRY_IMAGE/migrate:latest )
    - ( cd services/web  && docker build . -f ./Dockerfile -t $CI_REGISTRY_IMAGE/web:latest )
    - ( cd services/get  && docker build . -f ./Dockerfile -t $CI_REGISTRY_IMAGE/get:latest  --build-arg "version=${CI_COMMIT_SHA}-`date -u +%Y%m%d.%H%M%S`" )
    - ( cd services/sync && docker build . -f ./Dockerfile -t $CI_REGISTRY_IMAGE/sync:latest --build-arg "version=${CI_COMMIT_SHA}-`date -u +%Y%m%d.%H%M%S`" )
    - docker push $CI_REGISTRY_IMAGE/api:latest
    - docker push $CI_REGISTRY_IMAGE/migrate:latest
    - docker push $CI_REGISTRY_IMAGE/web:latest
    - docker push $CI_REGISTRY_IMAGE/get:latest
    - docker push $CI_REGISTRY_IMAGE/sync:latest
