stages:
  - deploy

docker:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:latest --build-arg "version=`git rev-parse --short HEAD`-`date -u +%Y%m%d.%H%M%S`"
    - docker push $CI_REGISTRY_IMAGE:latest
    - |
      if [ "$CI_COMMIT_TAG" ] ; then
        docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG  --build-arg "version=${CI_COMMIT_TAG}-`date -u +%Y%m%d.%H%M%S`"
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      fi
