image: "rust:1.23"

services:
  - postgres:10

variables:
  POSTGRES_DB: fetch_test
  POSTGRES_USER: fetch
  POSTGRES_PASSWORD: "adfjkv389gqyh39gheilfgeuj"
  CARGO_HOME: $CI_PROJECT_DIR/cargo


stages:
  - test
  - style
  - deploy

cargo:
  stage: test
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq --no-install-recommends build-essential libclang-dev libpq-dev
  script:
    - du -hs target
    - du -hs cargo
    - rustc --version && cargo --version && rustup --version
    - cargo install diesel_cli --no-default-features --features postgres 
    - echo "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}" > .env
    - cat .env
    - diesel migration run
    - cargo build --verbose --release
    - cargo test --verbose --jobs 1 --release
  cache:
    paths:
      - target/
      - cargo/

rustfmt:
  stage: style
  allow_failure: true
  script:
    - rustc --version && cargo --version && rustup --version
    - rustup component add rustfmt-preview
    - $CARGO_HOME/bin/rustfmt --write-mode diff src/**.rs

pages:
  stage: deploy
  script:
    - rustc --version && cargo --version && rustup --version
    - cargo doc
    - rm -rf public
    - mv target/doc public
    - echo "<meta http-equiv=refresh content=1;url=fetch_rs/index.html>" > public/index.html
  artifacts:
    paths:
    - public
  only:
    - master

