package fetcher

import (
	"bytes"
	"encoding/json"
	"fmt"
	log "github.com/sirupsen/logrus"
	"io/ioutil"
	"net/http"
	"net/url"
	"path"
)

// Init creates an API with the given configuration
func Init(url string) *API {
	api := new(API)
	api.url = url
	api.client = &http.Client{}

	return api
}

func (api *API) get(endpoint string) ([]byte, error) {
	apiUrl, err := url.Parse(api.url)
	if err != nil {
		return nil, err
	}

	apiUrl.Path = path.Join(apiUrl.Path, endpoint)
	r, err := http.NewRequest("GET", apiUrl.String(), nil)
	if err != nil {
		return nil, err
	}

	r.Header.Add("Content-Type", "application/json")

	log.Debug("sending Fetch API get request to ", endpoint)
	resp, err := api.client.Do(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	log.Debug("reading response to request for ", endpoint)
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	return body, nil
}

// GetSeries returns a list of all series from the API
func (api *API) GetSeries() ([]Series, error) {
	body, err := api.get("/series/")

	if err != nil {
		return nil, err
	}

	series := new([]Series)
	err = json.Unmarshal(body, &series)

	if err != nil {
		return nil, err
	}

	return *series, nil
}

// GetProviders returns a list of all providers from the API
func (api *API) GetProviders() ([]Provider, error) {
	body, err := api.get("/provider/")

	if err != nil {
		return nil, err
	}

	providers := new([]Provider)
	err = json.Unmarshal(body, &providers)

	if err != nil {
		return nil, err
	}

	return *providers, nil
}

func (api *API) PostEpisodeCount(id int, count int) error {

	values := map[string]int{"current_count": count}
	data, err := json.Marshal(values)

	apiUrl, err := url.Parse(api.url)
	if err != nil {
		return err
	}

	apiUrl.Path = path.Join(apiUrl.Path, "series", fmt.Sprint(id), "count")
	// addition of "/" is to accommodate stupid API url rules
	r, err := http.NewRequest("POST", apiUrl.String()+"/", bytes.NewBuffer(data))
	if err != nil {
		return err
	}
	r.Header.Add("Content-Type", "application/json")

	_, err = api.client.Do(r)

	return err
}

// API is a struct to interact with the API
type API struct {
	url    string
	client *http.Client
}

// Provider is a struct of what is returned from the /provider/ end-point
// generated by http://www.jsonstruct.com/
type Provider struct {
	BaseProvider        string            `json:"base_provider"`
	BaseProviderOptions map[string]string `json:"base_provider_options"`
	ID                  int               `json:"id"`
	Name                string            `json:"name"`
	RegexFindCount      string            `json:"regex_find_count"`
}

// Series is a struct of what is returned from /series/ end-point
// generated by http://www.jsonstruct.com/
type Series struct {
	CurrentCount           int               `json:"current_count"`
	EndDate                string            `json:"end_date"`
	ID                     int               `json:"id"`
	InfoURL                string            `json:"info_url"`
	MediaType              string            `json:"media_type"`
	MediaTypeOptions       map[string]string `json:"media_type_options"`
	NextRelease            string            `json:"next_release"`
	Provider               string            `json:"provider"`
	ProviderID             int               `json:"provider_id"`
	ReleaseSchedule        string            `json:"release_schedule"`
	ReleaseScheduleOptions map[string]string `json:"release_schedule_options"`
	ReleaseTime            string            `json:"release_time"`
	SavePath               string            `json:"save_path"`
	SearchTitle            string            `json:"search_title"`
	StartDate              string            `json:"start_date"`
	Title                  string            `json:"title"`
	TotalCount             int               `json:"total_count"`
}
