[package]
authors = ["David Barnett <david@barnett.net.nz>"]
name = "fetch-rocket"
version = "0.1.0"

[dependencies]
diesel = "0.9.1"
dotenv = "0.8.0"
lazy_static = "0.2.2"
r2d2 = "0.7.1"
r2d2-diesel = "0.9.0"
rocket = "0.1.3"
rocket_codegen = "0.1.3"
serde = "0.8.21"
serde_derive = "0.8.21"
serde_json = "0.8.4"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.9.0"

[dependencies.rocket_contrib]
default_features = false
features = ["json", "tera_templates"]
version = "0.1.3"
