version: "2"

services:

  api:
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    command: /bin/sh /bin/watch-dev '/bin/fetch-api' '/opt/fetch-api' '/etc/fetch.toml'
    restart: on-failure
    volumes:
      - ./watch-dev.sh:/bin/watch-dev:ro
      - ../../services/api/config.toml:/etc/fetch.toml:ro
      - ../../services/api/target/debug:/opt:ro
    links:
      - db
    depends_on:
      - db
      - migrate
    environment:
      DATABASE_URL: postgres://postgres@db/postgres

  get:
    build:
      context: ../../services/get
      dockerfile: Dockerfile
    command: /bin/sh /bin/watch-dev '/usr/local/bin/fetch' '/opt/fetch' '/etc/fetcherd.toml'
    restart: on-failure
    volumes:
      - ./watch-dev.sh:/bin/watch-dev:ro
      - ../../services/get/config.toml:/etc/fetcherd.toml:ro
      - ../../services/get/bin:/opt:ro
    links:
      - api
    depends_on:
      - api
    extra_hosts:
      # FIXME: https://github.com/docker/for-linux/issues/264
      host.docker.internal: 172.17.0.1

  sync:
    build:
      context: ../../services/sync
      dockerfile: Dockerfile
    command: /bin/sh /bin/watch-dev '/usr/local/bin/sitesync' '/opt/sitesync' '/etc/sitesync.toml'
    restart: on-failure
    volumes:
      - ./watch-dev.sh:/bin/watch-dev:ro
      - ../../services/sync/config.toml:/etc/sitesync.toml:ro
      - ../../services/sync/bin:/opt:ro
    links:
      - api
    depends_on:
      - api

  web:
    build:
      context: ../../services/web
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ../../services/web/public:/www:ro
    ports:
      - 3000:80
    links:
      - api
    depends_on:
      - api

  migrate:
    build:
      context: ../../services/api
      dockerfile: Dockerfile-migrate
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
