version: "2"

services:

  api:
    build:
      context: ../services/api
      dockerfile: Dockerfile
    command: /bin/sh /bin/watch-dev
    volumes:
      - ./api/config.toml:/etc/fetch.toml:ro
      - ./api/watch-dev.sh:/bin/watch-dev:ro
      - ../services/api/target/debug:/opt
    links:
      - db
    depends_on:
      - db
      - migrate
    environment:
      DATABASE_URL: postgres://postgres@db/postgres

  web:
    build:
      context: ../services/web
      dockerfile: Dockerfile
    volumes:
      - ./web/service.d:/etc/nginx/service.d:ro
      - ../services/web/public:/www:ro
    ports:
      - 3000:80
    links:
      - api
    depends_on:
      - api

  migrate:
    build:
      context: ../services/api
      dockerfile: Dockerfile-migrate
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
