FROM rust:1.28 AS build

RUN cargo install diesel_cli --no-default-features --features postgres --version '1.2.0'

FROM debian:stretch-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq5

WORKDIR /opt

COPY --from=build /usr/local/cargo/bin/diesel /bin/diesel
COPY migrations /opt/migrations

CMD ["/bin/diesel", "migration", "run", "--migration-dir", "/opt/migrations"]

# vim:set ft=dockerfile:
