fetchapi = "http://api:3000"

[webui]
enable = true
host = "0.0.0.0:3000"


[Transmission]
rpc = "http://host.docker.internal:9091/transmission/rpc"
user = "transmission"
password = "p@ssw0rd"

[log]
tojson = true
